substitutions:
  name: jk-bms
  device_description: "Monitoring Skripsi JK-BMS 8S"
  external_components_source: github://syssi/esphome-jk-bms@main
  mac_address: 20:23:04:33:7B:67
  # PENTING: Untuk JK-BD4A8S4P Hardware V11+ pakai ini:
  protocol_version: JK02_32S

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.2.0

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: "Re"
  password: "12345679"
  ap:
    ssid: "BMS-Emergency"
    password: "password123"

logger:
  level: DEBUG
  logs:
    esp32_ble_tracker: INFO
    esp32_ble_client: INFO

api:

mqtt:
  broker: broker.mqtt.cool
  port: 1883
  topic_prefix: skripsi/bms_unit_1
  
  # --- TAMBAHAN: PESAN STATUS KONEKSI ---
  birth_message:
    topic: skripsi/bms_unit_1/status
    payload: "online"
  will_message:
    topic: skripsi/bms_unit_1/status
    payload: "offline"

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0

# --- SENSOR (DATA BERUPA ANGKA) ---
sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    # Data Global
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    capacity_remaining:
      name: "${name} capacity remaining"
    state_of_charge:
      name: "${name} state of charge"
    balancing_current:
      name: "${name} balancing current"
    
    # Perbaikan Error MOS Temperature
    power_tube_temperature:
      name: "${name} MOS/Power Tube Temperature"
      
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
    temperature_sensor_2:
      name: "${name} temperature sensor 2"

    # Data Per Cell (Hanya 1-8 untuk baterai 8S)
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    cell_voltage_5:
      name: "${name} cell voltage 5"
    cell_voltage_6:
      name: "${name} cell voltage 6"
    cell_voltage_7:
      name: "${name} cell voltage 7"
    cell_voltage_8:
      name: "${name} cell voltage 8"
    
    # Statistik
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    charging_cycles:
      name: "${name} charging cycles"
    
    # Total Runtime ANGKA (detik) masuk sini
    total_runtime:
      name: "${name} total runtime seconds"

# --- BINARY SENSOR (STATUS ON/OFF) ---
binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    online_status:
      name: "${name} online status"

# --- SWITCH (TOMBOL KONTROL) ---
switch:
  - platform: jk_bms_ble
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    balancer:
      name: "${name} balancer"

# --- TEXT SENSOR (DATA BERUPA HURUF/TEKS) ---
text_sensor:
  - platform: jk_bms_ble
    errors:
      name: "${name} errors"
    
    # Perbaikan Error: Formatted harus masuk Text Sensor
    total_runtime_formatted:
      name: "${name} total runtime formatted"
      
    charge_status:
      name: "${name} charge status"