// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQampK8P14r7gqOH9NDjuE9pAOE9WpB24',
    appId: '1:989560527793:web:8e9b8b8059ee7e1af67b90',
    messagingSenderId: '989560527793',
    projectId: 'bmsv1-f5b30',
    authDomain: 'bmsv1-f5b30.firebaseapp.com',
    databaseURL: 'https://bmsv1-f5b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmsv1-f5b30.firebasestorage.app',
    measurementId: 'G-439TMNT1F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdE4sPK7bL587UaFkAGKMeaF5y4SPkWMU',
    appId: '1:989560527793:android:19c4e17370ca9702f67b90',
    messagingSenderId: '989560527793',
    projectId: 'bmsv1-f5b30',
    databaseURL: 'https://bmsv1-f5b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmsv1-f5b30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2mj-Q8k2Dpg3SAo1MXYfBacxcz_Mj9tQ',
    appId: '1:989560527793:ios:fa4c93345dc5c89cf67b90',
    messagingSenderId: '989560527793',
    projectId: 'bmsv1-f5b30',
    databaseURL: 'https://bmsv1-f5b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmsv1-f5b30.firebasestorage.app',
    iosBundleId: 'com.example.bmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2mj-Q8k2Dpg3SAo1MXYfBacxcz_Mj9tQ',
    appId: '1:989560527793:ios:fa4c93345dc5c89cf67b90',
    messagingSenderId: '989560527793',
    projectId: 'bmsv1-f5b30',
    databaseURL: 'https://bmsv1-f5b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmsv1-f5b30.firebasestorage.app',
    iosBundleId: 'com.example.bmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQampK8P14r7gqOH9NDjuE9pAOE9WpB24',
    appId: '1:989560527793:web:8e9b8b8059ee7e1af67b90',
    messagingSenderId: '989560527793',
    projectId: 'bmsv1-f5b30',
    authDomain: 'bmsv1-f5b30.firebaseapp.com',
    databaseURL: 'https://bmsv1-f5b30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmsv1-f5b30.firebasestorage.app',
    measurementId: 'G-439TMNT1F8',
  );
}
